### ISSUE TITLE
"Size" field in index entry has wrong size

### ISSUE THREAD

**Issue by knittl** [juretta/git-in-haskell-from-the-bottom-up#1]
I was dissecting the Git index format for a session on the Git internals and found your wonderful blog post about reimplementing git clone and friends with Haskell.

I found one discrepancy and wonder if this implementation will write correct index files.

The Git technical documentation has a file describing the index format, especially the layout of each index entry at https://github.com/git/git/blob/master/Documentation/technical/index-format.txt#L80

The Haskell implementation uses `Int64` for the size (https://github.com/juretta/git-in-haskell-from-the-bottom-up/blob/master/src/Git/Store/Index.hs#L65), while this field should only occupy 32 bits.

**Comment by knittl** [comment]
Nevermind, it looks like the file size is truncated in `instance Binary IndexEntry` through function `coerce` to 32 bit. I was only confused by the `IndexEntry` definition.

**Comment by juretta** [comment]
No worries, thanks for following up ad closing this.
